-- Allow new section 'testimony_psychology' in professional_resources
ALTER TABLE public.professional_resources
  DROP CONSTRAINT IF EXISTS professional_resources_section_check;

ALTER TABLE public.professional_resources
  ADD CONSTRAINT professional_resources_section_check
  CHECK (section IN (
    'protocols',
    'gender_violence',
    'psychological_damage',
    'sexual_abuse',
    'communication_regime',
    'audience_tips',
    'bibliography',
    'informed_consent',
    'report_models',
    'testimony_psychology'
  ));

-- Insert bibliographic references for the new section
INSERT INTO public.professional_resources
  (section, title, description, author, source, resource_type, role_tag, sort_order, url)
VALUES
  ('testimony_psychology',
   'Lamb et al. (2018) — Tell Me What Happened (NICHD)',
   'Manual completo del Protocolo NICHD para entrevistas forenses a NNyA en casos de sospecha de abuso. 2.ª ed. Wiley-Blackwell.',
   'Lamb, M. E., Brown, D. A., Hershkowitz, I., Orbach, Y., & Esplin, P. W.',
   'Wiley-Blackwell',
   'link', 'forensic', 1,
   'https://onlinelibrary.wiley.com/doi/book/10.1002/9781118881248'),
  ('testimony_psychology',
   'Amado, Arce, Fariña & Vilariño (2016) — Meta-análisis CBCA en adultos',
   'Meta-análisis sobre la validez del CBCA aplicado a adultos. International Journal of Clinical and Health Psychology.',
   'Amado, B. G., Arce, R., Fariña, F., & Vilariño, M.',
   'IJCHP',
   'link', 'forensic', 2,
   'https://doi.org/10.1016/j.ijchp.2016.01.002'),
  ('testimony_psychology',
   'Otgaar et al. (2019) — Falsos recuerdos y trauma reprimido',
   'Revisión crítica sobre la posibilidad experimental de inducir falsos recuerdos traumáticos. Perspectives on Psychological Science.',
   'Otgaar, H., Howe, M. L., Patihis, L., et al.',
   'Perspectives on Psychological Science',
   'link', 'forensic', 3,
   'https://doi.org/10.1177/1745691619862306'),
  ('testimony_psychology',
   'Hershkowitz, Lamb & Katz (2014) — NICHD revisado',
   'Estudio sobre el Protocolo NICHD revisado con componente de soporte emocional. Psychology, Public Policy, and Law.',
   'Hershkowitz, I., Lamb, M. E., & Katz, C.',
   'PPPL',
   'link', 'forensic', 4,
   'https://doi.org/10.1037/a0037391'),
  ('testimony_psychology',
   'Arce, Fariña, Carballal & Novo (2009) — Protocolo de evaluación forense en violencia de género',
   'Protocolo integrado SVA + secuelas psicológicas validado en muestras forenses. Psicothema.',
   'Arce, R., Fariña, F., Carballal, A., & Novo, M.',
   'Psicothema',
   'link', 'forensic', 5,
   'https://www.psicothema.com/pdf/3622.pdf'),
  ('testimony_psychology',
   'Brewin (2018) — Memory and Forgetting',
   'Revisión sobre memoria, olvido y trauma con implicancias para la valoración forense del relato. Current Psychiatry Reports.',
   'Brewin, C. R.',
   'Current Psychiatry Reports',
   'link', 'forensic', 6,
   'https://doi.org/10.1007/s11920-018-0950-7'),
  ('testimony_psychology',
   'Manzanero (2010) — Memoria de testigos: obtención y valoración de la prueba testifical',
   'Manual iberoamericano de referencia sobre psicología del testimonio. Editorial Pirámide.',
   'Manzanero, A. L.',
   'Pirámide',
   'link', 'forensic', 7,
   'https://www.antoniomanzanero.com/'),
  ('testimony_psychology',
   'Intebi (2011) — Proteger, reparar, penalizar (ASI)',
   'Obra de referencia argentina sobre evaluación e intervención en abuso sexual infantil. Granica.',
   'Intebi, I.',
   'Granica',
   'link', 'forensic', 8,
   'https://www.editorialgranica.com/'),
  ('testimony_psychology',
   'Ministerio Público de la Acusación — Santa Fe (Ley 12.734)',
   'Sistema procesal penal acusatorio de la Provincia de Santa Fe. Marco normativo de actuación pericial.',
   NULL,
   'MPA Santa Fe',
   'link', 'forensic', 9,
   'https://www.mpa.santafe.gov.ar/');